/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projeto_individual;


import java.util.Random;

/**
 *
 * @author Lucas
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    
    
            
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pbcpu = new javax.swing.JProgressBar();
        pbmemoria = new javax.swing.JProgressBar();
        pbdisco = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnleitura = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblmaximocpu = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblmediacpu = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblminimocpu = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblmaximodisco = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblmediadisco = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblminimodisco = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblmaximomemoria = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblmediamemoria = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblminimomemoria = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CPU");

        jLabel2.setText("DISCO");

        jLabel3.setText("MEMORIA");

        btnleitura.setText("Fazer Leitura");
        btnleitura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnleituraActionPerformed(evt);
            }
        });

        jLabel4.setText("Máximo:");

        lblmaximocpu.setText("0");

        jLabel6.setText("Média:");

        lblmediacpu.setText("0");

        jLabel8.setText("Mínimo:");

        lblminimocpu.setText("0");

        jLabel5.setText("Máximo:");

        lblmaximodisco.setText("0");

        jLabel7.setText("Média:");

        lblmediadisco.setText("0");

        jLabel9.setText("Mínimo:");

        lblminimodisco.setText("0");

        jLabel10.setText("Máximo:");

        lblmaximomemoria.setText("0");

        jLabel11.setText("Média:");

        lblmediamemoria.setText("0");

        jLabel12.setText("Mínimo:");

        lblminimomemoria.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblmaximomemoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblmediamemoria)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblminimomemoria)
                        .addGap(203, 203, 203))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(pbdisco, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(jLabel1)
                                    .addComponent(pbcpu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(pbmemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblmaximodisco)
                                        .addGap(62, 62, 62)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblmediadisco)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblminimodisco))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblmaximocpu)
                                        .addGap(63, 63, 63)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblmediacpu)
                                        .addGap(53, 53, 53)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblminimocpu)))
                                .addGap(77, 77, 77)))
                        .addComponent(btnleitura)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(pbcpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblmaximocpu)
                    .addComponent(jLabel6)
                    .addComponent(lblmediacpu)
                    .addComponent(jLabel8)
                    .addComponent(lblminimocpu))
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(pbdisco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblmaximodisco)
                            .addComponent(jLabel7)
                            .addComponent(lblmediadisco)
                            .addComponent(jLabel9)
                            .addComponent(lblminimodisco))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnleitura)
                        .addGap(28, 28, 28)))
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(pbmemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblmaximomemoria)
                    .addComponent(jLabel11)
                    .addComponent(lblmediamemoria)
                    .addComponent(jLabel12)
                    .addComponent(lblminimomemoria))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Criando variaveis onde vou poder armazenar os valores sem perdelos 
    // ao clicar no botão
    Integer contador = 0, somacpu = 0, somamemoria = 0, somadisco = 0;
    private void btnleituraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnleituraActionPerformed
       Random random = new Random();
       Integer cpu = random.nextInt(101), memoria = random.nextInt(101),
               disco = random.nextInt(101);
       somacpu += cpu;
       somamemoria += memoria;
       somadisco += disco;

    // Verificando se é o primeiro click do botão
       if (contador.equals(0)){  
         lblminimocpu.setText(cpu.toString());
         lblminimodisco.setText(disco.toString());
         lblminimomemoria.setText(memoria.toString());
         
       }
       
     // Fazendo a verificação do valor minimo
       if(Integer.parseInt(lblminimocpu.getText()) > cpu){
                lblminimocpu.setText(cpu.toString());
       }
       
       if(Integer.parseInt(lblminimodisco.getText()) > disco){
                lblminimodisco.setText(disco.toString());
       }
       
       if(Integer.parseInt(lblminimomemoria.getText()) > memoria){
                lblminimomemoria.setText(memoria.toString());
       }
       contador += 1;
       
       
       // Descobrindo e adicionando a media de cada barra
       Integer cpumedia = somacpu / contador,
               memoriamedia = somamemoria / contador,
               discomedia = somadisco / contador;
       lblmediacpu.setText(cpumedia.toString());
       lblmediamemoria.setText(memoriamedia.toString());
       lblmediadisco.setText(discomedia.toString());
       
       // Verificando a máxima de cada barra 
       if ( Integer.parseInt(lblmaximocpu.getText()) < cpu){
           lblmaximocpu.setText(cpu.toString());
       }
       
       if ( Integer.parseInt(lblmaximomemoria.getText()) < memoria){
           lblmaximomemoria.setText(memoria.toString());
       }
       
       if ( Integer.parseInt(lblmaximodisco.getText()) < disco){
           lblmaximodisco.setText(disco.toString());
       }
       
     
       // Exibindo os valores da barra
       pbcpu.setStringPainted(true);
       pbmemoria.setStringPainted(true);
       pbdisco.setStringPainted(true);
       
       // Definindo os valores das barras
       pbcpu.setValue(cpu);
       pbmemoria.setValue(memoria);
       pbdisco.setValue(disco);
    }//GEN-LAST:event_btnleituraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnleitura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblmaximocpu;
    private javax.swing.JLabel lblmaximodisco;
    private javax.swing.JLabel lblmaximomemoria;
    private javax.swing.JLabel lblmediacpu;
    private javax.swing.JLabel lblmediadisco;
    private javax.swing.JLabel lblmediamemoria;
    private javax.swing.JLabel lblminimocpu;
    private javax.swing.JLabel lblminimodisco;
    private javax.swing.JLabel lblminimomemoria;
    private javax.swing.JProgressBar pbcpu;
    private javax.swing.JProgressBar pbdisco;
    private javax.swing.JProgressBar pbmemoria;
    // End of variables declaration//GEN-END:variables
}
